name: Gujarati News Indexing Cron Job

on:
  schedule:
    - cron: '30 5 * * *'  # Runs at 5:30 and 17:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-indexing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start MongoDB
        run: |
          sudo systemctl start mongod
          sleep 5  # Give MongoDB time to start

      - name: Run the indexing script
        run: python indexing.py
