name: Run Indexing Script

on:
  schedule:
    - cron: "30 5 * * *"  # Runs once a day at 05:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run indexing script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  # Use the MongoDB Atlas connection string stored in GitHub Secrets
        run: python indexing.py
